### ISSUE TITLE
A way to install on windows, or a windows alternative?

### ISSUE THREAD

**Issue by denizsincar29** [mcb30/pycdio#1]
Hello everyone. 

I've spent countless hours searching for ways to read CDs at a low-level on Windows using Python, but all my efforts have been unsuccessful, and it's been frustrating. Is it truly impossible to read CD disks on Windows and access the CD drive? Also, I'm curious if there is a method to install pycdio on Windows. Any insights or guidance would be greatly appreciated.---

**Comment by mcb30** [comment]
This repository is just an old and unused personal fork - you probably want to raise this question with the upstream.

**Comment by denizsincar29** [comment]
Ah ok. Than maybe it' would be great to have that disclamer in the readme that it's a fork? Because yes, i found the upstream a few days ago but installed linux.
